keepassx2pass: Substitute empty string for None
If keepassx2pass.py is given an xml file containing passwords with an empty
title, like <title></title>, ElementTree.text returns None. This commit
substitutes an empty string; which will produce a password with name '_',
instead of raising AtttributeError, as shown in this exception::

    Traceback (most recent call last):
      File "contrib/importers/keepassx2pass.py", line 80, in <module>
        main(sys.argv[1])
      File "contrib/importers/keepassx2pass.py", line 77, in main
        import_group(group)
      File "contrib/importers/keepassx2pass.py", line 71, in import_group
        import_entry(entry, npath)
      File "contrib/importers/keepassx2pass.py", line 58, in import_entry
        print "Importing " + path_for(element, path)
      File "contrib/importers/keepassx2pass.py", line 37, in path_for
        title = cleanTitle(space_to_camelcase(element.find('title').text))
      File "contrib/importers/keepassx2pass.py", line 16, in space_to_camelcase
        for word in value.split(" "):
    AttributeError: 'NoneType' object has no attribute 'split'